name: cd

on: [push, pull_request]
permissions:
  contents: write
jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2

        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages 

      - name: Create 404 page
        run: |
          cp index.html 404.html
          
      - name: Push 404 page
        run: |
          git add .
          git commit -m "Updating 404 file"
          git push origin gh-pages
          
